kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.rhsso.instanceName }}
  labels:
    app: {{ .Values.rhsso.instanceName }}
spec:
  host: {{ .Values.rhsso.route.sso.host }}
  to:
    kind: Service
    name: {{ .Values.rhsso.instanceName }}
    weight: 100
  port:
    targetPort: {{ .Values.rhsso.instanceName }}
  tls:
    termination: reencrypt
  wildcardPolicy: None