kind: Secret
apiVersion: v1
metadata:
  name: credential-example-keycloak
  labels:
    app: keycloak
    keycloak: example-keycloak
data:
  ADMIN_PASSWORD: {{ .Values.rhsso.secrets.credential-example-keycloak.ADMIN_PASSWORD.value | quote }}
  ADMIN_USERNAME: {{ .Values.rhsso.secrets.credential-example-keycloak.ADMIN_USERNAME.value | quote }}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  labels:
    app: keycloak
data:
  POSTGRES_DATABASE: {{ .Values.rhsso.secrets.keycloak-db-secret.POSTGRES_DATABASE.value | quote }}
  POSTGRES_HOST: {{ .Values.rhsso.secrets.keycloak-db-secret.POSTGRES_HOST.value | quote }}
  POSTGRES_PASSWORD: {{ .Values.rhsso.secrets.keycloak-db-secret.POSTGRES_PASSWORD.value | quote }}
  POSTGRES_USERNAME: {{ .Values.rhsso.secrets.keycloak-db-secret.POSTGRES_USERNAME.value | quote }}
type: Opaque
