apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rhsso.instanceName }}
  labels:
    app: {{ .Values.rhsso.instanceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.rhsso.instanceName }}
  selector:
    app: {{ .Values.rhsso.instanceName }}
    component: {{ .Values.rhsso.instanceName }}