apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: role-binding-argocd
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: argocd
subjects:
- kind: ServiceAccount
  name: <application-controller-name> 
  namespace: <application-controller-namespace>